### ISSUE TITLE
Python code-style suggestion

### ISSUE THREAD

**Issue by HwangWonYo** [seongahjo/Mosaicer#12]
It looks like there are no unified rules for indents.
I suggest using 4 spaces for indents as [PEP 8](https://www.python.org/dev/peps/pep-0008/#indentation) Style Guide recommended.

**Comment by seongahjo** [comment]
@HwangWonYo 옙 감사합니다.
이전까지는 vi로만 작업해서 일정한 coding convetion 적용이 힘들었는데
이제는 PyCharm이 있는 환경을 제공받아서 쉽게 적용했습니다.
조언 감사합니다. 다시 한번 확인해보고 안되있으면 적용하겠습니다.
