### ISSUE TITLE
How about add CODE_OF_CONDUCT.md to Mosaicer?

### ISSUE THREAD

**Issue by bbvch13531** [seongahjo/Mosaicer#26]
Type of issue
 - Doc

## Description
- I think opensource project should have code of conduct. 😄
How about add CODE_OF_CONDUCT.md to Mosaicer?
If this looks good on you, could I send PR that add CODE_OF_CONDUCT.md?

**Comment by seongahjo** [comment]
@bbvch13531 
Thank you for your attention to our project.
Well, Looks good to me. We'll thank you if you do so
